# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print("NumPy 버전:", np.__version__)
print("\nNumPy 구성:")
print(np.show_config())

NumPy 버전: 1.25.2

NumPy 구성:
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_m

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
a1= np.array([1,2,3])
print("a1의 메모리사이즈: ",a1.nbytes)

a1의 메모리사이즈:  24


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
n1 = np.zeros(10)
n1[4]=1
n1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
a2=np.arange(10, 50)
a2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [17]:
reversed_a2 = a2[::-1]
reversed_a2

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

sorted함수나 reverse 함수는 ndarray에 사용 불가능

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
a3= np.arange(9)
m1=a3.reshape(3,3)
m1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [20]:
a4= np.array([1,2,0,0,4,0])
a4.nonzero()

(array([0, 1, 4]),)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [22]:
i1 = np.eye(3)
i1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
i2=np.identity(3)
i2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [26]:
r1= np.random.random((3,3,3))
r1

array([[[0.90802958, 0.16082969, 0.63529441],
        [0.88619143, 0.61995578, 0.96234256],
        [0.78978399, 0.74073872, 0.29846095]],

       [[0.82279318, 0.75069652, 0.87033868],
        [0.18167097, 0.77223712, 0.25555268],
        [0.6257444 , 0.43587326, 0.48240029]],

       [[0.99453344, 0.99362485, 0.77002048],
        [0.87127916, 0.2209    , 0.9735858 ],
        [0.87646631, 0.30987505, 0.2425196 ]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [28]:
r2=np.random.random((10,10))
print(r2)
print("최솟값:", r2.min())
print("최댓값:", r2.max())

[[0.7599122  0.40354304 0.66284665 0.52967356 0.43281612 0.24863673
  0.86654787 0.24499955 0.43609677 0.93335478]
 [0.99221742 0.62590594 0.38284334 0.00348588 0.76514271 0.58951899
  0.82389465 0.08353948 0.42435563 0.81723992]
 [0.97978249 0.66108174 0.86601577 0.99801485 0.15535399 0.20781346
  0.80581844 0.39471062 0.85015221 0.05259875]
 [0.72006272 0.21405588 0.3651158  0.72897999 0.65762761 0.91853613
  0.95839782 0.81095671 0.72144965 0.1233245 ]
 [0.07743644 0.81560875 0.88020593 0.30877616 0.06900207 0.1628913
  0.71585347 0.868651   0.57823832 0.97957484]
 [0.88096537 0.36700849 0.38956112 0.74698051 0.57961783 0.59157837
  0.81325194 0.29123364 0.09330471 0.81569534]
 [0.66067106 0.77641965 0.28446145 0.90940278 0.68922914 0.46695717
  0.24429969 0.14716758 0.48992006 0.23728197]
 [0.58605329 0.74531705 0.66307549 0.63292735 0.346695   0.33949635
  0.66943095 0.57255659 0.61376995 0.18695069]
 [0.89564031 0.43804759 0.90303666 0.80863916 0.76777283 0.17214106
  0.60654781 

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [29]:
r3= np.random.random(30)
print(r3.mean())

0.5146175052945161


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [34]:
n= np.random.randint(1,10)
a2 = np.ones(n*n)
m2 = a2.reshape(n,n)
m2[1:-1,1:-1] = 0
m2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [35]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [37]:
m3= np.zeros((5,5))
values=np.array([1,2,3,4])
np.fill_diagonal(m3[1:], values)
m3

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [39]:
# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Fill the matrix with checkerboard pattern
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1
matrix

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [40]:
import numpy as np

shape = (6, 7, 8)
value = 100

index = np.unravel_index(value, shape)

print("Index (x, y, z) of the 100th element:", index)

Index (x, y, z) of the 100th element: (1, 5, 4)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [46]:
m5=np.random.random((5,5))
mean5= np.mean(m5)
s5= np.std(m5)
m5= (m5-mean5)/s5
m5

array([[ 1.11436335, -0.78873725,  0.80246444, -0.05003326, -0.79486595],
       [-0.52324982, -0.66133515,  0.67606228,  1.13183681, -1.05881981],
       [ 1.41277507,  1.10014674, -1.2827402 ,  0.1565269 , -1.29475735],
       [ 0.96118792, -0.91574311, -0.54020846,  0.20875624,  0.76174683],
       [ 1.74413014,  1.30788584, -0.71532049, -1.32330743, -1.42876426]])

#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [47]:
# Define custom dtype for RGBA colors
rgba_dtype = np.dtype([('r', np.uint8),  # Red channel
                       ('g', np.uint8),  # Green channel
                       ('b', np.uint8),  # Blue channel
                       ('a', np.uint8)]) # Alpha channel

# Example RGBA color
color = np.array((255, 128, 0, 255), dtype=rgba_dtype)

print("RGBA Color:", color)

RGBA Color: (255, 128, 0, 255)


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [48]:
m1 = np.random.random((5,3))
m2 = np.random.random((3,2))
m1 @ m2

array([[1.09702864, 0.99426142],
       [0.86717152, 0.91938374],
       [0.31700488, 0.34408574],
       [0.78576994, 0.9164706 ],
       [0.4972736 , 0.66646423]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [49]:
# Create a 1D array
array = np.array([1, 5, 7, 3, 9, 2, 6, 4, 8])

# Negate elements between 3 and 8 in place
array[(array > 3) & (array < 8)] *= -1

print("Modified array:", array)

Modified array: [ 1 -5 -7  3  9  2 -6 -4  8]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [50]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [51]:
z=np.array([1,2,3])
z**z

array([ 1,  4, 27])

In [52]:
2<<z>>2

array([1, 2, 4])

In [53]:
z<-z

array([False, False, False])

In [54]:
1j*z

array([0.+1.j, 0.+2.j, 0.+3.j])

In [55]:
z/1/1

array([1., 2., 3.])

In [56]:
z<z>z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [57]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-57-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-57-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-57-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [59]:
# Generate two random arrays
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

# Find common values between Z1 and Z2
common_values = np.intersect1d(Z1, Z2)

print(Z1)
print(Z2)
print("Common values between Z1 and Z2:", common_values)

[6 1 8 2 8 5 6 0 7 3]
[6 4 5 9 1 7 1 1 8 5]
Common values between Z1 and Z2: [1 5 6 7 8]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [60]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-60-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [61]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [62]:
import numpy as np

# Define start and end dates for July 2016
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')

# Generate array of dates corresponding to the month of July 2016
dates_july_2016 = np.arange(start_date, end_date, dtype='datetime64[D]')

print("Dates corresponding to the month of July 2016:")
print(dates_july_2016)

Dates corresponding to the month of July 2016:
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [64]:
A=np.array([1,2,3])
B=np.array([4,5,6])

a=np.add(A,B)
n_a=np.negative(A)
b=np.divide(n_a,2)
c=np.multiply(a,b)
c

array([ -2.5,  -7. , -13.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [65]:
# Generate a random array of positive numbers
random_array = np.random.rand(5) * 10  # Random positive numbers between 0 and 10

# Extract the integer part using astype(int)
integer_part_astype = random_array.astype(int)

print("Integer part using astype(int):", integer_part_astype)

Integer part using astype(int): [6 9 7 0 4]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [75]:
matrix = np.tile(np.arange(5), (5, 1))
matrix

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 32. Create a random vector of size 10 and sort it (★★☆)

In [77]:
a=np.array([3,6,1,6,8,2,8,4,2,9])
b=np.sort(a)
b

array([1, 2, 2, 3, 4, 6, 6, 8, 8, 9])

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [78]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A,B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [79]:
# Generate random cartesian coordinates
cartesian_coords = np.random.rand(10, 2)  # 10 rows, 2 columns

# Extract x and y coordinates
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]

# Convert cartesian coordinates to polar coordinates
r = np.sqrt(x**2 + y**2)  # distance from origin to (x,y)
theta = np.arctan2(y, x)  # angle from the x-axis

# Stack r and theta to get polar coordinates
polar_coords = np.column_stack((r, theta))

print("Cartesian Coordinates:")
print(cartesian_coords)
print("\nPolar Coordinates:")
print(polar_coords)

Cartesian Coordinates:
[[0.29582882 0.40065003]
 [0.55357149 0.97803008]
 [0.25201452 0.09352022]
 [0.58900775 0.52873605]
 [0.22529536 0.07267585]
 [0.25912757 0.08545932]
 [0.51361416 0.8182009 ]
 [0.53763146 0.68037273]
 [0.08235166 0.88351972]
 [0.247964   0.58758929]]

Polar Coordinates:
[[0.49803127 0.93477868]
 [1.12382571 1.05574709]
 [0.26880727 0.35533888]
 [0.79151244 0.7315277 ]
 [0.23672722 0.31204182]
 [0.272856   0.31856387]
 [0.9660498  1.01023197]
 [0.86715318 0.90205879]
 [0.88734936 1.47785623]
 [0.63776745 1.17146754]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [81]:
z=np.random.random(10)
z[z.argmax()]=0
z

array([0.21283947, 0.44345709, 0.46880344, 0.4617929 , 0.08653902,
       0.        , 0.69527461, 0.29979294, 0.24071741, 0.69284338])

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [82]:
# Create vector Z and scalar v
Z = np.arange(100)
v = np.random.uniform(0, 100)

# Compute absolute differences between elements of Z and scalar v
distances = np.abs(Z - v)

# Find the index of the minimum difference
closest_index = np.argmin(distances)

# The closest value is Z[closest_index]
closest_value = Z[closest_index]

print("Scalar v:", v)
print("Closest value in Z:", closest_value)


Scalar v: 18.12440058008108
Closest value in Z: 18


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [83]:
Z = np.arange(9).reshape(3, 3)

# Iterate over each element of the array and print index and value
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [90]:
n = 5  # Size of the 2D array
p = 4  # Number of elements to place
value_to_place = 1  # Value that you want to place

Z = np.zeros((n, n))
np.put(Z, np.random.choice(range(n * n), p, replace=False), value_to_place)
print(Z)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [87]:
# column 1
Z = np.random.randint(0,10,(3,3))
n=0
sorted_indices = np.argsort(Z[:, n])

sorted_Z = Z[sorted_indices]

print("원본 배열:")
print(Z)
print("\n%d번째 열을 기준으로 정렬된 배열:" % n)
print(sorted_Z)

원본 배열:
[[2 7 7]
 [7 9 6]
 [3 1 4]]

0번째 열을 기준으로 정렬된 배열:
[[2 7 7]
 [3 1 4]
 [7 9 6]]


In [88]:
# column 2
n=1
sorted_indices = np.argsort(Z[:, n])

# n번째 열을 기준으로 배열 정렬
sorted_Z = Z[sorted_indices]

print("원본 배열:")
print(Z)
print("\n%d번째 열을 기준으로 정렬된 배열:" % n)
print(sorted_Z)

원본 배열:
[[2 7 7]
 [7 9 6]
 [3 1 4]]

1번째 열을 기준으로 정렬된 배열:
[[3 1 4]
 [2 7 7]
 [7 9 6]]


In [89]:
# column 3
n=2
sorted_indices = np.argsort(Z[:, n])

# n번째 열을 기준으로 배열 정렬
sorted_Z = Z[sorted_indices]

print("원본 배열:")
print(Z)
print("\n%d번째 열을 기준으로 정렬된 배열:" % n)
print(sorted_Z)

원본 배열:
[[2 7 7]
 [7 9 6]
 [3 1 4]]

2번째 열을 기준으로 정렬된 배열:
[[3 1 4]
 [7 9 6]
 [2 7 7]]
