# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print("NumPy Version : ",np.__version__)
#print(np.__config__)
print(np.__config__.show())

NumPy Version :  1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macro

np.__config__는 구성 정보 객체를 반환하고, np.__config__.show()는 이 구성 정보를 보기 좋게 포맷하여 출력합니다.

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
a=np.zeros(10)

null vector = zero vector

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
print('a array의 메모리 크기:', a.nbytes)

a array의 메모리 크기: 80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
v1 = np.arange(10, 50)
v1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
reverse_v1 = v1[::-1]
reverse_v1

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
m1 = np.arange(0,9).reshape(3,3)
m1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
a2=np.array([1,2,0,0,4,0])
non_zero_indices = np.nonzero(a2)
non_zero_indices

(array([0, 1, 4]),)

In [ ]:
np.where(a2 != 0)

(array([0, 1, 4]),)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
identity_matrix =np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
identity_matrix = np.identity(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
random_array = np.random.random((3,3,3))
random_array

array([[[0.39270705, 0.36831758, 0.21491407],
        [0.60952708, 0.72919513, 0.29007993],
        [0.85422647, 0.66584337, 0.45000972]],

       [[0.37857402, 0.29812041, 0.18157738],
        [0.37182937, 0.13592951, 0.99672799],
        [0.63955393, 0.627007  , 0.34459601]],

       [[0.65076776, 0.28265686, 0.02389511],
        [0.03858769, 0.92055947, 0.69163365],
        [0.80247529, 0.59745002, 0.53899916]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
random_array2 = np.random.random((10,10))
min= np.min(random_array2)
max = np.max(random_array2)
print('Min: ',min)
print("Max: ",max)

Min:  0.008307347257335174
Max:  0.9960292318306341


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
random_array3 = np.random.random(30)
print('Mean: ', np.mean(random_array3))

Mean:  0.44258775552574975


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
# 크기 정해주기
k = np.random.randint(1,10)
print('크기 : ', k)

array= np.zeros((k,k))

# 가장자리 1로 만들기
array[0,:]=1
array[-1, :]=1
array[:,0]=1
array[:,-1]=1

array

크기 :  7


array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
a= np.nan
a

nan

In [ ]:
0 * np.nan

nan

In [ ]:
np.nan == np.nan

False

In [ ]:
np.inf > np.nan

False

In [ ]:
np.nan - np.nan

nan

In [ ]:
np.nan in set([np.nan])

True

In [ ]:
0.3 == 3 * 0.1

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
matrix = np.zeros((5, 5))

# fill_diagonal :주 대각성분을 특정 값으로 채움
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])

print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
matrix= np.zeros((8,8))

matrix[1::2, ::2] =1
matrix[::2, 1::2] =1

matrix

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [ ]:
matrix = np.tile(np.array([[0,1],[1,0]]),(4,4))
matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
matrix = np.random.random((5,5))

x_bar = np.mean(matrix, axis=0)
s = np.std(matrix, axis =0)

normalized_matrix = (matrix - x_bar)/ s

print(matrix,'\n')

print(normalized_matrix)

[[0.51125445 0.47812357 0.38177684 0.87706474 0.31834503]
 [0.43660853 0.15149234 0.60518648 0.09111353 0.07158764]
 [0.90029434 0.9129437  0.08313561 0.39682884 0.74526831]
 [0.69915368 0.99976786 0.73378975 0.23918159 0.88648467]
 [0.70823402 0.79188548 0.19771309 0.36822468 0.37187865]] 

[[-0.85674788 -0.60392546 -0.07632023  1.82468826 -0.54046966]
 [-1.31402821 -1.649188    0.84317516 -1.14706733 -1.37208833]
 [ 1.52650736  0.78755563 -1.30544909  0.00887108  0.89834184]
 [ 0.29432132  1.06540428  1.37247244 -0.58720805  1.37426749]
 [ 0.34994741  0.40015355 -0.83387827 -0.09928397 -0.36005134]]


In [ ]:
rand= np.random.random((5,5))
norm = (rand- rand.mean())/rand.std()
print(norm)

[[ 0.16852332  0.18481488  1.05048541  0.81661797 -0.98045007]
 [-1.12926989  0.26607457 -1.22153443  1.3004543  -0.21773108]
 [-1.32052845  0.60544599 -0.5248819  -1.3437061  -1.1878369 ]
 [ 1.30389423 -0.05198044 -0.43853691 -1.2456343   1.74425522]
 [ 1.17030316  1.33547608  0.59741103  0.46436633 -1.34603202]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
color_dtype = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])

뭔소리여

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
m1 = np.random.random((5,3))
m2 = np.random.random((3,2))

m1 @ m2

array([[0.29403963, 0.45684187],
       [0.14272151, 0.60922274],
       [0.52177461, 0.21045384],
       [0.71961438, 0.48714799],
       [1.34631215, 0.50048883]])

In [ ]:
np.dot(m1, m2)

array([[0.29403963, 0.45684187],
       [0.14272151, 0.60922274],
       [0.52177461, 0.21045384],
       [0.71961438, 0.48714799],
       [1.34631215, 0.50048883]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
# 1차원 배열 생성
arr = np.array([1,2,3,4,5,6,7,8,9,10])

# 3과 8 사이의 모든 요소 부정
arr[(arr > 3) & (arr < 8)] *= -1

print(arr)

[ 1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z= np.array([1,2,3])
z**z

array([ 1,  4, 27])

In [ ]:
2<<z>>2

array([1, 2, 4])

비트 시프트 연산??

In [ ]:
z<-z

array([False, False, False])

In [ ]:
1j*z

array([0.+1.j, 0.+2.j, 0.+3.j])

In [ ]:
z/1/1

array([1., 2., 3.])

In [ ]:
z<z>z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)

<ipython-input-55-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [ ]:
np.array(0) // np.array(0)

<ipython-input-56-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [ ]:
np.array([np.nan]).astype(int).astype(float)

<ipython-input-57-ea171f4782f5>:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3